# ## EC2 Instance Setup
- name: Provision AWS EC2 Instance
  hosts: localhost
  roles:
    - { role: ec2-provision }

- name: Update and install instance requirements
  remote_user: ec2-user
  become: yes
  vars:
    ANSIBLE_HOST_KEY_CHECKING: false
    ansible_ssh_private_key_file:  "{{ ec2key_priv_secondary_dir }}"
  hosts: webservers
  roles:
    - { role: setup }

- name: Complete local build requriements
  hosts: localhost
  roles:
    - { role: local }
  
- name: Complete git requriements
  remote_user: ec2-user
  vars:
    ANSIBLE_HOST_KEY_CHECKING: false
    ansible_ssh_private_key_file:  "{{ ec2key_priv_secondary_dir }}"
  hosts: webservers
  roles:
    - { role: deploy }

## Elastic Load Balencer Setup
- name: Setup Load Balencer
  hosts: localhost
  gather_facts: true
  roles:
    - { role: load_balencer }

# Tear down services: Procede with cautionn
- name: Tear down values
  hosts: localhost
  gather_facts: true
  vars:
    ANSIBLE_HOST_KEY_CHECKING: false
  roles:
    - { role: tear-down }