# ## EC2 Instance Setup
- name: Provision AWS EC2 Instance
  hosts: localhost
  roles:
    - { role: ec2-provision }

- name: Update and install instance requirements
  remote_user: ec2-user
  become: yes
  vars:
    ansible_ssh_private_key_file:  "{{ ec2key_priv_secondary_dir }}"
  hosts: webservers
  roles:
    - { role: setup }

- name: Complete local build requriements
  hosts: localhost
  roles:
    - { role: local }
  
- name: Complete git requriements
  remote_user: ec2-user
  vars:
    ansible_ssh_private_key_file:  "{{ ec2key_priv_secondary_dir }}"
  hosts: webservers
  roles:
    - { role: deploy }

- name: Delete npm build after ec2 setup
  ansible.builtin.file:
    path: ./roles/deploy/files/build
    state: absent
  tags:
    - local

## Elastic Load Balencer Setup
- name: Setup Load Balencer
  hosts: localhost
  gather_facts: true
  roles:
    - { role: load_balencer }