- name: Provision AWS EC2 Instance
  hosts: localhost
  roles:
    - { role: ec2-provision }

- name: Update and install instance requirements
  remote_user: ec2-user
  become: yes
  vars:
    ansible_ssh_private_key_file:  "{{ ec2key_priv_secondary_dir }}"
  hosts: webservers
  roles:
    - { role: setup }
  
- name: Complete git requriements
  remote_user: ec2-user
  vars:
    ansible_ssh_private_key_file:  "{{ ec2key_priv_secondary_dir }}"
  hosts: webservers
  roles:
    - { role: deploy }