ec2_key_name: "527-ec2-key"
ec2_private_key_dir: "/Users/hannah/Desktop/University2023/COMPX527/527-web-app/ansible/527-ec2-key.pem"
ec2key_secondary: "527-ec2-key-secondary"
ec2key_priv_secondary_dir: "/Users/hannah/Desktop/University2023/COMPX527/527-web-app/ansible/527-ec2-key-secondary.pem"

# I know the key locations are insecure we are coping with that for now.